account_id= "58725f493ed309e525add8440d49b70d"
name = "cloud-flare"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-11-09"
